"""add booking vehicle model

Revision ID: 053198af1798
Revises: dddc644f1e15
Create Date: 2026-02-04 09:54:34.975522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053198af1798'
down_revision: Union[str, Sequence[str], None] = 'dddc644f1e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['manual_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_vehicles_id'), 'booking_vehicles', ['id'], unique=False)
    op.drop_constraint(op.f('manual_bookings_driver_id_fkey'), 'manual_bookings', type_='foreignkey')
    op.drop_column('manual_bookings', 'driver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_bookings', sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('manual_bookings_driver_id_fkey'), 'manual_bookings', 'drivers', ['driver_id'], ['id'])
    op.drop_index(op.f('ix_booking_vehicles_id'), table_name='booking_vehicles')
    op.drop_table('booking_vehicles')
    # ### end Alembic commands ###
