"""add driver detail in tour packages

Revision ID: 143bd7961b17
Revises: a4c5ddc91e6b
Create Date: 2026-01-20 15:21:21.994755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143bd7961b17'
down_revision: Union[str, Sequence[str], None] = 'a4c5ddc91e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_package_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_package_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_package_drivers_id'), 'tour_package_drivers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_package_drivers_id'), table_name='tour_package_drivers')
    op.drop_table('tour_package_drivers')
    # ### end Alembic commands ###
