"""add slug column

Revision ID: 512766f8258b
Revises: aca2a02322c2
Create Date: 2026-03-10 12:44:34.453472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512766f8258b'
down_revision: Union[str, Sequence[str], None] = 'aca2a02322c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_companies_slug'), table_name='companies')
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.create_index(op.f('idx_companies_slug'), 'companies', ['slug'], unique=True)
    # ### end Alembic commands ###
