"""Create booking_vehicle_drivers table

Revision ID: 74c9846bb712
Revises: 7e870f0a286f
Create Date: 2026-02-10 19:18:02.993966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74c9846bb712'
down_revision: Union[str, Sequence[str], None] = '7e870f0a286f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_vehicle_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['manual_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_vehicle_drivers_id'), 'booking_vehicle_drivers', ['id'], unique=False)
    op.drop_index(op.f('ix_booking_drivers_id'), table_name='booking_drivers')
    op.drop_table('booking_drivers')
    op.drop_index(op.f('ix_booking_vehicles_id'), table_name='booking_vehicles')
    op.drop_table('booking_vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_vehicles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['manual_bookings.id'], name=op.f('booking_vehicles_booking_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('booking_vehicles_vehicle_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_vehicles_pkey'))
    )
    op.create_index(op.f('ix_booking_vehicles_id'), 'booking_vehicles', ['id'], unique=False)
    op.create_table('booking_drivers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['manual_bookings.id'], name=op.f('booking_drivers_booking_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('booking_drivers_driver_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_drivers_pkey'))
    )
    op.create_index(op.f('ix_booking_drivers_id'), 'booking_drivers', ['id'], unique=False)
    op.drop_index(op.f('ix_booking_vehicle_drivers_id'), table_name='booking_vehicle_drivers')
    op.drop_table('booking_vehicle_drivers')
    # ### end Alembic commands ###
