"""make booking vehicle and driver table

Revision ID: 7e870f0a286f
Revises: f0162b0503c1
Create Date: 2026-02-10 17:20:19.698314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e870f0a286f'
down_revision: Union[str, Sequence[str], None] = 'f0162b0503c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['manual_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_drivers_id'), 'booking_drivers', ['id'], unique=False)
    op.drop_constraint(op.f('booking_vehicles_driver_id_fkey'), 'booking_vehicles', type_='foreignkey')
    op.drop_column('booking_vehicles', 'driver_id')
    op.drop_column('booking_vehicles', 'seats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_vehicles', sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('booking_vehicles', sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('booking_vehicles_driver_id_fkey'), 'booking_vehicles', 'drivers', ['driver_id'], ['id'])
    op.drop_index(op.f('ix_booking_drivers_id'), table_name='booking_drivers')
    op.drop_table('booking_drivers')
    # ### end Alembic commands ###
