"""make faq document table

Revision ID: 9002d263f937
Revises: 74c9846bb712
Create Date: 2026-02-16 14:38:32.452649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '9002d263f937'
down_revision: Union[str, Sequence[str], None] = '74c9846bb712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_documents_company_id'), 'faq_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_faq_documents_id'), 'faq_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faq_documents_id'), table_name='faq_documents')
    op.drop_index(op.f('ix_faq_documents_company_id'), table_name='faq_documents')
    op.drop_table('faq_documents')
    # ### end Alembic commands ###
