"""Add WhatsApp fields and company_id

Revision ID: 9ad86dc04170
Revises: 5dab7f5db9e8
Create Date: 2026-01-29 12:05:08.651426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad86dc04170'
down_revision: Union[str, Sequence[str], None] = '5dab7f5db9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chat_sessions', 'companies', ['company_id'], ['id'])
    op.add_column('companies', sa.Column('whatsapp_access_token', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('whatsapp_phone_number_id', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('whatsapp_business_account_id', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('whatsapp_template_lang', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('whatsapp_webhook_verify_token', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'whatsapp_webhook_verify_token')
    op.drop_column('companies', 'whatsapp_template_lang')
    op.drop_column('companies', 'whatsapp_business_account_id')
    op.drop_column('companies', 'whatsapp_phone_number_id')
    op.drop_column('companies', 'whatsapp_access_token')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'company_id')
    # ### end Alembic commands ###
