"""add payment ref and transport type to manual booking

Revision ID: a13d52483de7
Revises: 053198af1798
Create Date: 2026-02-06 14:35:07.715152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13d52483de7'
down_revision: Union[str, Sequence[str], None] = '053198af1798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_bookings', sa.Column('payment_ref', sa.String(length=255), nullable=True))
    op.add_column('manual_bookings', sa.Column('transport_type', sa.String(length=20), nullable=True))
    op.drop_column('manual_bookings', 'email')
    op.drop_column('manual_bookings', 'guest_name')
    op.drop_column('manual_bookings', 'country_code')
    op.drop_column('manual_bookings', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_bookings', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('manual_bookings', sa.Column('country_code', sa.VARCHAR(length=10), server_default=sa.text("'+91'::character varying"), autoincrement=False, nullable=True))
    op.add_column('manual_bookings', sa.Column('guest_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('manual_bookings', sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('manual_bookings', 'transport_type')
    op.drop_column('manual_bookings', 'payment_ref')
    # ### end Alembic commands ###
