"""add embedding column to tour package

Revision ID: aca2a02322c2
Revises: 9002d263f937
Create Date: 2026-02-16 16:25:09.186129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'aca2a02322c2'
down_revision: Union[str, Sequence[str], None] = '9002d263f937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_packages', sa.Column('embedding', Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_packages', 'embedding')
    # ### end Alembic commands ###
