"""added stripe keys and webhook to company model

Revision ID: daf4cdae77e7
Revises: a13d52483de7
Create Date: 2026-02-09 15:06:32.970971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf4cdae77e7'
down_revision: Union[str, Sequence[str], None] = 'a13d52483de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('stripe_publishable_key', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('stripe_secret_key', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('stripe_webhook_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'stripe_webhook_secret')
    op.drop_column('companies', 'stripe_secret_key')
    op.drop_column('companies', 'stripe_publishable_key')
    # ### end Alembic commands ###
