"""add chat session and chat message models

Revision ID: dddc644f1e15
Revises: 9ad86dc04170
Create Date: 2026-01-29 15:27:25.321026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dddc644f1e15'
down_revision: Union[str, Sequence[str], None] = '9ad86dc04170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(length=10), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.add_column('chat_sessions', sa.Column('context', sa.JSON(), nullable=True))
    op.add_column('chat_sessions', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.add_column('chat_sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('chat_sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'created_at')
    op.drop_column('chat_sessions', 'is_active')
    op.drop_column('chat_sessions', 'last_message_at')
    op.drop_column('chat_sessions', 'context')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
