"""Add driver and vehicle to manual booking, vehicle photos

Revision ID: f0162b0503c1
Revises: daf4cdae77e7
Create Date: 2026-02-10 12:44:40.819535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0162b0503c1'
down_revision: Union[str, Sequence[str], None] = 'daf4cdae77e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_table('vehicle_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_photos_id'), 'vehicle_photos', ['id'], unique=False)
    op.add_column('booking_vehicles', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.alter_column('booking_vehicles', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'booking_vehicles', 'vehicles', ['vehicle_id'], ['id'])
    op.add_column('drivers', sa.Column('license_number', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'drivers', ['license_number'])
    op.drop_column('drivers', 'vehicle_number')
    op.drop_column('drivers', 'vehicle_type')
    op.drop_column('drivers', 'seats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('vehicle_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('vehicle_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_column('drivers', 'is_active')
    op.drop_column('drivers', 'license_number')
    op.drop_constraint(None, 'booking_vehicles', type_='foreignkey')
    op.alter_column('booking_vehicles', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('booking_vehicles', 'vehicle_id')
    op.drop_index(op.f('ix_vehicle_photos_id'), table_name='vehicle_photos')
    op.drop_table('vehicle_photos')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
